### ISSUE TITLE
Failure when running migrator.list()

### ISSUE THREAD

**Issue by valango** [balmasi/migrate-mongoose#16]
If there is no migrations collection present in the database, but migration files exist,
call to `migrator.list()` (as in examples here) results in:

`(node:2911) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: createdMigration.toJSON is not a function`

The exception was thrown from `lib.js`:

```javascript
       var createdMigration = MigrationModel.create({
           name: migrationName,
           createdAt: timestamp
       });
       return createdMigration.toJSON();  // This is a Promise, not document! (valango)
```

**Comment by balmasi** [comment]
@valango fixed in latest release! Thanks for pointing it out!
