### ISSUE TITLE
Babel dependency unmet when doing migrate --up

### ISSUE THREAD

**Issue by coyotte508** [balmasi/migrate-mongoose#19]
```bash
/home/ubuntu/code/novelia>migrate up
Synchronizing database with file system migrations...
Cannot find module 'babel-runtime/regenerator'
```

I have node 7.4.0.

```bash
npm install babel-runtime
```

This fixes it when run in the project's directory.

**Comment by balmasi** [comment]
Thanks @coyotte508 I'll see if I can spare some time this weekend to integrate babel-env so it recognizes what you need based on your environment

**Comment by balmasi** [comment]
I've made the major decision to remove babel support, so I'm afraid I have to close this issue
