### ISSUE TITLE
per environment config files? programmatic access?

### ISSUE THREAD

**Issue by raistlinthewiz** [balmasi/migrate-mongoose#2]
is per environment config files possible? (one for development, one for production)

Can i programatically access migrate-mongoose?

**Comment by balmasi** [comment]
Yes you can have per environment config.

I suggest setting an environment variable with the option you want preceded with MIGRATE_ such as `MIGRATE_dbConnectionUri`.

You can also programmatically access migrate-mongoose by requiring it and making a `new` migrator object from it.

the constructor options (and their defaults, if any) are:
```javascript
{
   templatePath,
   migrationsPath = './migrations', 
   dbConnectionUri,
   es6Templates = false,
   collectionName = 'migrations',
   autosync = false 
}
```

**Comment by balmasi** [comment]
@raistlinthewiz I added some docs for this if you still need.

https://github.com/balmasi/migrate-mongoose/tree/master/examples/programmatic-usage
