### ISSUE TITLE
Hard to debug Unexpected Token errors

### ISSUE THREAD

**Issue by emmya** [balmasi/migrate-mongoose#28]
Running with es6 set to true, I get this error: 
Unexpected Token when parsing migration. If you are using an ES6 migration file, use option --es6

It'd be helpful to see the full error since it's not obvious - syntax looks ok to me.

**Comment by emmya** [comment]
Btw I figured it out - was from this syntax:
const { thing } = obj;

**Comment by balmasi** [comment]
Thanks for pointing this out 🙌  I fixed this in 4.0.0
