### ISSUE TITLE
Update README with complete example

### ISSUE THREAD

**Issue by maximumgs** [balmasi/migrate-mongoose#31]
While attempting to run the example, the last one that has the User model and migration script, everything executes as though it worked, but the database is not updated.

I read a Closed issue in which someone seemed to have a similar problem, and indicated that it is fixed by creating a connection in the migration script. This works, but has very unpredictable behavior.

This library is excellent and does exactly what I was looking for, but it is in need of a complete example than can be used "out-of-the-box". 

Thanks.

**Comment by NetOperatorWibby** [comment]
Glad to see I'm not the only one with this issue.

**Comment by balmasi** [comment]
Thanks for pointing this out. I'll pick this up this week and see what I can do to make it ultra clear.

**Comment by balmasi** [comment]
I updated the docs. I really appreciate the feedback @NetOperatorWibby !

**Comment by balmasi** [comment]
Let me know if it's still unclear.

Sometimes it's hard to see things from a new user's perspective
