### ISSUE TITLE
get rid of babel?

### ISSUE THREAD

**Issue by bonesoul** [balmasi/migrate-mongoose#33]

**Comment by rkmax** [comment]
Today I've installed the package in a project a found a lot of nasty warnings about babel. I think the right way is just leave babel for development and before publish compile

**Comment by krismeister** [comment]
I think the issue with removing babel, is that the migrations need to be evaluated in node.

 if you've written with ES6 style imports or advanced Ecma Script features like the spread operator it could not be able to be evaluated on your current node.

I think the alternative options, is to make anyone using migrate-mongoose to convert their migration files manually.

**Comment by MadRabbit** [comment]
+1 this is a bit too much.

after a quick look, it seems like they're using babel-cli to launch the `.bin/migrate` script. this could be easily pre-compiled during the publish phase

**Comment by ns3777k** [comment]
I ran into similar issue but this project seems to be dead so i wrote my own. https://github.com/ns3777k/mongoose-migrate

**Comment by balmasi** [comment]
Project is now alive again ;)

Sorry it took so long. Been away. You'll be happy to know that babel's been removed in 4.0.0
