### ISSUE TITLE
Not working with secure connection (authorization option)

### ISSUE THREAD

**Issue by Kaushik-junkis** [balmasi/migrate-mongoose#34]
Hello,

When we have authorization enabled in security option at mongo side, we have no option to set the username, password. Is there any way to provide username & password for authenticating the user?

**Comment by halk** [comment]
Have you tried setting username and password in the mongoDB URL as described in https://docs.mongodb.com/manual/reference/connection-string/?

**Comment by balmasi** [comment]
halk's suggestion is the answer you're looking for :) Thanks @halk
