### ISSUE TITLE
[Urgent!] Comparison of django migration framework

### ISSUE THREAD

**Issue by yiakwy** [balmasi/migrate-mongoose#35]
Hi，I am looking for a migration framework to record my mongoose ORM changes and apply them to mongo database. 

However I cannot see it clearly how it works  from the introduction markdown file. Could you explain it further with an example.

I want it this way:

I modify my models' schema in models/user.js. Then I run "migrate apply" which will generate migration patches and apply them step by step into my new database:

It drops the old database and then fills data values using a new relationship mapper. 

Is it possible in migrate-mongoose?

**Comment by balmasi** [comment]
In mongodb you don't have to explicitly migrate your schema changes. It's a "Soft" schema.

The way you use these migrations and a tool like this library is to mainly do DATA migrations.

if you want all your `user.name` fields to become `user.fullname` and remove the `user.name` key, you'll have to create a migration and write the `up()` function (renaming `name` to `fullname`) and optionally a `down()` function (undoing that, as in renaing `fullname` to `name`)

I hope that clears it up
