### ISSUE TITLE
Unable to up migration

### ISSUE THREAD

**Issue by GMaker01** [balmasi/migrate-mongoose#37]
I have made a migration with cmd: migrate -d <db Uri> create initDb
This created me a file 1543573729152-initDB.js in the application folder.
I have created my models in application/models/ but unable to import them to migration
I have used these codes for importing
```
1. require('../application/models/<modelName>/index.js');
2. require('mongoose').model(<modelName>).modelName;
3. require('mongoose').model(<modelName>).schema;
```
```
exports.up = async function up(done) {
// Instead of mongoose.model(<modelName>,<modelNameSchema>) also used direct import variable
    await mongoose.model(<modelName>,<modelNameSchema>).insertMany([
        { name: 'Diabetes' },
        { name: 'Hypertension' },
        { name: 'Cardiovascular Disease' },
        { name: 'Other' },
        { name: 'None' },
    ]);
done();
};
```
I am new to the service and I dont know what I am doing wrong..

**Comment by balmasi** [comment]
I've added more examples both in the main readme and in the examples folder.

Explore https://github.com/balmasi/migrate-mongoose/tree/master/examples/config-file-usage
