### ISSUE TITLE
Babel version incompatible when doing migrate --up

### ISSUE THREAD

**Issue by xiandalisay** [balmasi/migrate-mongoose#40]
I executed the command **migrate up**. Then, there's this error. 

`Require Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error
to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.`

My project's @babel/core dependency is "^7.3.4".

**Comment by balmasi** [comment]
This should no longer be an issue cause I've removed the requirement for babel
