### ISSUE TITLE
New Server Discover and Monitoring engine for MongoClient

### ISSUE THREAD

**Issue by colinwong** [balmasi/migrate-mongoose#48]
Not a major concern but am getting this deprecation warning when I run migrations.

`(node:10591) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

Running on the following:

`"mongodb": "^3.3.2", "mongoose": "^5.7.1"`

Is there any way to get rid of it?

**Comment by ecgan** [comment]
I'm having this issue too.

**Comment by chris-aeviator** [comment]
It's a deprecation warning, meaning it will break with a future update but is still runable now
