### ISSUE TITLE
Migrate command not exiting

### ISSUE THREAD

**Issue by kmiyashiro** [balmasi/migrate-mongoose#6]
I have this migration:

```js
require('../models/user');

/**
 * Make any changes you need to make to the database here
 */
export async function up() {
  await this('User').update({}, {
    $set: {
      role: 'user',
    },
  });
}

/**
 * Make any changes that UNDO the up function side effects here (if possible)
 */
export async function down() {
  await this('User').update({}, {
    $unset: {
      role: '',
    },
  });
}
```

I run it with `--es6` and it never exits. If I use `DEBUG=*` I can see that it is doing things, but it just never exits. This is the final log of the down command:

```
  mquery update +14ms users {} { '$setOnInsert': { createdAt: 2016-06-12T18:30:49.032Z },
  '$set': { updatedAt: 2016-06-12T18:30:49.032Z },
  '$unset': { role: 0 } } {}
```

I also tried replacing `await` with `return`.

**Comment by kmiyashiro** [comment]
I also forgot to mention that the migration is not actually taking effect, even if it marks the migration itself as `up` after running it.

**Comment by kmiyashiro** [comment]
Nevermind, figured out that I had to initiate my own db connection and that this doesn't share one. Would be nice to include that in the readme since it doesn't mention it anywhere and the implication is that you only need the mongoose model.

**Comment by balmasi** [comment]
@kmiyashiro doesn't it make sense for it to use its own connection to the DB? 
Sharing a connection with your application makes it dependant on your implementation.

Also for people who may be a little confused, the `this('Model')` is the model name you register for your schema.

for example 
`export default mongoose.model('ticket', Ticket);`

Becomes `this('ticket')`.

**Comment by kmiyashiro** [comment]
It is not immediately clear that you must initiate a db connection because it is not in any of the examples. Since it was not in any of the examples, I assumed it was not needed and there was some magic/assumptions going on in this library.

**Comment by kmiyashiro** [comment]
Also, it's pretty weird to have to initiate a db connection from within a migration template.

**Comment by coreytrampe** [comment]
Well, I'm glad this is documented somewhere. 👍
