### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by manasovdan** [balmasi/migrate-mongoose#8]
Hi, I'm really like your package but have some suggestions:
I think package should use config file by default without passing it as a param every time;
And the second - use a JS file that exports JSON-object because sometimes it's needed to do some operations like getting vars from env

**Comment by manasovdan** [comment]
Found this [lib](https://github.com/mccraveiro/mongoose-migration). It inits config file and that's really cool feature

**Comment by balmasi** [comment]
@manasovdan 100% agree. I've been a bit busy but I'll gladly take a PR.

I should get to implementing it in the next few weeks though.

**Comment by balmasi** [comment]
@manasovdan happy to say this has been added in 3.2
